/** Anthony Huberman, "Make It Thick" — footnotes 1–58 (sources only; no page markers). */
export const FOOTNOTES: string[] = [
  `Haraway, "Cyborg Manifesto," in Manifestly Haraway (Minneapolis: University of Minnesota Press, [1985], 2016), 57.`,
  `Reuleaux quoted in Jean-François Lyotard, "Considerations on Certain Partition-Walls as the Potentially Bachelor Elements of a Few Simple Machines," in The Bachelor Machine, Harald Szeemann, ed. (Venice: Alfieri Edizioni D'Arte, 1975), 98.`,
  `It's useful to note that Marx is writing at the height of slavery, in which the priority given to profit over other human values in the context of labor is made manifest with particular brutality.`,
  `The text would become incorporated into Marx's A Contribution to the Critique of Political Economy (1859), and ultimately into his three volumes of Capital (1867, 1885, and 1894).`,
  `Marx quoted in Gerald Raunig, A Thousand Machines (Los Angeles: Semiotext[e], 2010), 21.`,
  `Ibid. (emphasis mine).`,
  `In a short reflection on the nature of the typewriter, Martin Heidegger uses the term mechanism as a way to describe something that is not quite a tool and not quite a machine, but somewhere between the two. See Heidegger, Parmenides, trans. André Schuwer and Richard Rojcewicz (Bloomington and Indianapolis: Indiana University Press, 1992), 86.`,
  `Herbert A. Simon, Administrative Behavior: A Study of Decision-Making Processes in Administrative Organization (New York: The Macmillan Co., 1947).`,
  `Alexander, The Mantra of Efficiency: From Waterwheel to Social Control (Baltimore: Johns Hopkins University Press, 2008), vi.`,
  `Even the notion of productivity doesn't contain the same nuance, as it's easier to imagine someone protesting a demand to be more productive than a demand to be more efficient.`,
  `Easterling, Extrastatecraft: The Power of Infrastructure Space (London and New York: Verso, 2014), 18.`,
  `Heidegger's notion of the gigantic is a precursor to what would later become "big data," in which modern technological means of communication and control defined all subjects by their quantifiability and calculability.`,
  `Gilles Châtelet, To Live and Think Like Pigs, trans. Robin Mackay (New York and Falmouth, UK: Sequence Press and Urbanomic Media [1998], 2014), 128.`,
  `Nishant Shah, "Mechanical Labor," in Nervous Systems, Anselm Franke, Stephanie Hankey, and Marek Tuszynski, eds. (Berlin: Haus der Kulturen der Welt and Spector Books, 2016), 295.`,
  `Peter Gorsen, "The Humiliating Machine: Escalade of a New Myth," in The Bachelor Machine, ed. Harald Szeemann (Venice: Alfieri Edizioni D'Arte, 1975), 131.`,
  `Franklin, The Real World of Technology (Toronto: House of Anansi Press [1990], 2004), 3.`,
  `Barry Sanders, "Bang the Keys Swiftly: Type-Writers and Their Discontents," Cabinet 8 (Fall 2002).`,
  `Duchamp quoted in Maurizio Lazzarato, Marcel Duchamp and the Refusal of Work, trans. Joshua David Jordan (Los Angeles: Semiotext[e], 2014), 17. As Lazzarato would later put it, "A painted picture is the diagram of an idea," 25.`,
  `Les Levine quoted in Jack Burnham, Software (New York: Jewish Museum, 1970), 61.`,
  `After MoMA, the exhibition traveled to the newly opened Rice Museum in Houston (March 25–May 18, 1969) (not at Houston's University of St. Thomas, as indicated in the exhibition's catalogue), and the San Francisco Museum of Modern Art (June 23–August 24, 1969).`,
  `K. G. Pontus Hultén, The machine, as seen at the end of the mechanical age (New York: The Museum of Modern Art, 1968), 174.`,
  `In 1964 Hultén invited the engineer Billy Klüver, along with the artists Robert Rauschenberg, Yvonne Rainer, Robert Morris, Merce Cunningham, John Cage, David Tudor, Steve Paxton, and Öyvind Fahlström to perform at Five New York Evenings at the Moderna Museet in Stockholm. In 1966 a similar group would present 9 Evenings: Theater and Engineering in New York, and that same year Klüver and fellow Bell Labs engineer Fred Waldauser, along with artists Rauschenberg and Robert Whitman, would found E.A.T. At exactly the same time, the curator Maurice Tubman was preparing Art & Technology at the Los Angeles County Museum of Art, where artists were paired with corporations in hopes that, once again, they might be able to learn the skills, ask the questions, and realize the projects that needed the infrastructural and engineering capabilities of companies like IBM or American Cement Corp.`,
  `"Cybernetics" was a term first coined by the mathematician and philosopher Norbert Wiener 20 years prior, and referred to the notion that a machine could be connected back to itself, causing its output to become a new kind of input. Wiener defined cybernetics as "the scientific study of control and communication in the animal and the machine," thus using the same vocabulary being evoked by those critiquing technology—but without the critique. Wiener intuited that a system capable of generating feedback loops—a system, say, like a computer—and that could endlessly create, process, react to, change, and redeliver information could ultimately become entirely self-correcting and self-improving, and, potentially, develop an autonomous artificial intelligence.`,
  `The Software exhibition was by all accounts a catastrophe. Visitors (along with art critics reviewing the show) found malfunctioning or broken works and a general sense of chaos and mismanagement. The exhibition's second venue, the Smithsonian's Museum of History and Technology in Washington, DC, pulled out, and the show did not travel. On top of that, the exhibition wreaked havoc on the Jewish Museum's finances, which ultimately cost the museum's director, Karl Katz, his job.`,
  `Burnham, "Notes on art and information processing," in Software (New York: Jewish Museum, 1970), 10.`,
  `In a most basic sense, the entirety of human history can be thought of as a constant back and forth between hardware and software: tools yield rules yield tools yield rules yield tools, ad infinitum.`,
  `Serra quoted in Maurice Tubman, A Report on the Art and Technology Program at the Los Angeles County Museum of Art, 1967–1971 (Los Angeles: Los Angeles County Museum of Art, 1971), 300. This was part of a written statement by Serra following his collaboration with Kaiser Steel Corporation.`,
  `I thank Robert Snowden for underlining this point in his contribution to the yearlong section on "The Machine" I edited for CURA (issue 24, Winter 2017), 80.`,
  `Hultén, The machine, as seen..., 199.`,
  `Ibid., 13, 39.`,
  `Hultén gives an example on page 39 of his exhibition catalogue: "Around 1912, the American production engineer Frank B. Gilbreth analyzed in detail the movements of manual workers. His aim was to obtain better working conditions, but the result was that management often attempted to drive the workers harder in order to speed up production."`,
  `Nick Srnicek and Alex Williams, Inventing the Future: Postcapitalism and a World Without Work (New York and London: Verso, 2015), 63.`,
  `Châtelet, To Live and Think Like Pigs, 109, 111.`,
  `Franco Berardi, The Soul at Work: From Alienation to Autonomy (Los Angeles: Semiotext[e], 2009), 192.`,
  `See Erik Brynjolfsson and Andrew McAfee, The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies (New York: W. W. Norton, 2014).`,
  `Diedrich Diederichsen, "On All Channels," Artforum 51, no. 1 (September 2012): 452.`,
  `Joseph Vogl, "Taming Time: Media of Financialization," trans. Christopher Reid, Grey Room 46 (January 2012): 75.`,
  `Mike Judge makes no mistake in appointing a compression algorithm as the ultimate Holy Grail in his TV show Silicon Valley.`,
  `I use the term acceleration but do not align myself with the "accelerationism" developed by Nick Srnicek and Alex Williams, which locates an emancipatory value in acceleration, whereby the mechanisms of capitalism, when pushed to go even faster, will ultimately derail or implode. Their argument is sophisticated and nuanced, and while I can't argue against it in detail here, I ultimately can't accept what it requires in human "collateral": too many people will get destroyed in the process.`,
  `Keynes had predicted this back as far back as 1964: "We have reached the third degree where we devote our intelligences to anticipating what average opinion expects the average opinion to be. And there are some, I believe, who practice the fourth, fifth, and higher degrees." Keynes, quoted in Châtelet, To Live and Think Like Pigs, 72.`,
  `Vogl, "Taming Time," 77.`,
  `Ibid., 80.`,
  `Raunig, A Thousand Machines, 32.`,
  `Ibid.`,
  `Maurizio Lazzarato, Signs and Machines: Capitalism and the Production of Subjectivity (Los Angeles: Semiotext[e], 2014), 26–27.`,
  `Bratton, The Stack: From Software to Sovereignty (Cambridge, MA: MIT Press, 2015).`,
  `Flusser, Post-History, trans. Rodrigo Maltez Niovaes (Minneapolis: Univocal, [1983], 2013), 65.`,
  `Sure, there are ways to monetize love or friendship and extract profit from them, but that's only because we're trained and encouraged to do so, and rewarded if we do, not because they're intrinsic to the concepts or emotions themselves.`,
  `Franklin quoted in Meredith Meredith, "All Problems Can Be Illuminated; Not All Problems Can Be Solved," in The Present in Drag: 9th Berlin Biennial (Berlin: KW Institute of Contemporary Art, 2016), 158.`,
  `Mumford, Art and Technics (New York: Columbia University Press, [1952], 2000), 14.`,
  `Ibid., 47, 50.`,
  `Flusser, Post-History, 127.`,
  `Jane Livingston, "Thoughts on Art and Technology," in Maurice Tubman, A Report on the Art and Technology Program at the Los Angeles County Museum of Art, 1967–1971 (Los Angeles: Los Angeles County Museum of Art, 1971), 43.`,
  `Meredith, "All Problems Can Be Illuminated," 159.`,
  `Carrouges, "Directions for Use," in The Bachelor Machine, ed. Harald Szeemann (Venice: Alfieri Edizioni D'Arte, 1975), 21.`,
  `Deleuze and Guattari, "Balance-Sheet for 'Desiring-Machines,'" in Guattari, Chaosophy: Texts and Interviews, 1972–1977 (Los Angeles: Semiotext[e], 1995), 108.`,
  `In 1975, inspired by Duchamp, Harald Szeemann curated a traveling exhibition titled Le Macchine Celibi / The Bachelor Machines, which gathered together many of these works.`,
  `Lee, "Media Specificities," Artforum 51, no. 1 (September 2012): 406.`,
];

export const FOOTNOTE_COUNT = FOOTNOTES.length;
